### ISSUE TITLE
timeline only runs once

### ISSUE THREAD

**Issue by Jonatino** [edvin/tornadofx-guide#8]
I'm trying to make an event that runs every 5 seconds but for some reason my timeline only executes once.

Here is the code 

```
timeline {
                keyframe(5.seconds) {
                    println("Test")
                }

                isAutoReverse = true
                cycleCount = Timeline.INDEFINITE
            }
```

**Comment by edvin** [comment]
@thomasnield I think this is your baby - will you have a look when you get the chance? :)

**Comment by edvin** [comment]
Inside the `keyframe` clause you are supposed to add `keyvalue` directives. The reason that you see the `println` statement executed "only once" is actually because it is outputted as you build the time line, not while the animation is playing. I believe this is covered pretty well in the guide:

https://github.com/edvin/tornadofx-guide/blob/master/9.%20Builders%20VI%20-%20Shapes%20and%20Animation.md

Let me know if that doesn't clear it up :)

**Comment by thomasnield** [comment]
Haha I just got to this, I guess you got this covered @edvin? @Jonatino let us know if that doesn't resolve your question.

**Comment by PeptideWitch** [comment]
Following on from Jonatino's comment, I've read [elsewhere](https://tomasmikula.github.io/blog/2014/06/04/timers-in-javafx-and-reactfx.html) that JavaFX's version of the timeline used for animations can also take a function argument instead of just keyvalue actions. I'm really to get something like this working because I'm having thinking of how to use timers within the View class in order to update some of my variables based on external file changes.

So, for example, I have this label that I want to get the UI to check for changes every second.

`            label("Hi"){
                timeline {
                    keyframe (Duration.millis(1001.0)) {
                        val lastText = text
                        println(lastText)
                        text = DirectoryWatcher.main(lastText)
                    }
                        cycleCount = Timeline.INDEFINITE
                    }
                }`

This is feeding into the main function of an object DirectoryWatcher (which uses a WatchService to check for file changes)

`object DirectoryWatcher {

        @JvmStatic
        fun main(lastText: String): String {
            val myPath = Paths.get("src/pykotinterface")
            val myWatchService = FileSystems.getDefault().newWatchService()
            myPath.register(myWatchService, ENTRY_MODIFY)
            val myWatchKey = myWatchService.poll(100, TimeUnit.MILLISECONDS)

            if (myWatchKey != null) {
                val testid = File("src/pykotinterface/test").bufferedReader().readLine()
                myWatchKey.reset()
                return testid
            } else {
                return lastText
            }
        }
    }`

So am I correct in assuming that the timeline in TornadoFX can't be used to execute functions? How else should I go about getting the class to read an external file upon user changes?

**Comment by edvin** [comment]
No no no! :) The timeline is for UI related tasks and should not be (ab)used for I/O or other heavy tasks. In TornadoFX you can utilize `runAsync(daemon = true) { .. }` or simply use a `Timer` and a `TimerTask`. Just make sure that you wrap any UI related code in `runLater` so it runs back on the UI thread.

**Comment by PeptideWitch** [comment]
Thanks for the reply! I think I'm having trouble conceptualising exactly what I need in order to get what I'm after. Within my View class, I need a way to run (asynchronously) a watcher event that checks for a file modification, updates a string property and, accordingly, a bound label. Would you suggest taking the WatcherService out of the object and, instead of having that one-time if function, I simply bind the value of the label to the myWatchKey as a property?

**Comment by edvin** [comment]
I would create a ViewModel that exposes the string property. This ViewModel would start the WatcherService and update the string property when the file changes. Then you inject the ViewModel into your View and bind the label to the ViewModel property.

**Comment by PeptideWitch** [comment]
Thanks edvin.

I've tried my best for the past couple of hours, but I'm going to have to dig deeper into my understanding of the WatcherService before I get there. As per [the ViewModel tutorial](https://github.com/edvin/tornadofx-guide/blob/master/part1/11.%20Editing%20Models%20and%20Validation.md), I've created two new classes for the bound viewmodel and for the creation of the watcher, but within the watcher class I can't seem to update a string property because of the for loop that seems to be pervasive in the polling events for the Watch Key. When I get a solution to this, I'll post it here in case someone needs to see it.

Cheers! Wish me luck.

**Comment by bekwam** [comment]
This post has an example that uses SchedulerService in place of the busy loop.

**Comment by PeptideWitch** [comment]
Thanks bekwam, I'll check this out. Looks very promising already!

**Comment by PeptideWitch** [comment]
Works perfectly, excellent link! Thank you both.
